### ISSUE TITLE
audit, console & navbar issues

### ISSUE THREAD

**Issue by harshvchawla** [Toronto-Tech-Mentoring/TTM-Gatsby#40]
Just now made a build & encountered following issues:
1) (low priority?) npm audit "high" errors (& npm warnings, gatsy develop/lint warnings)
2) (low priority) browser console errors
3) navbar overlaps when pg scrolled up - see attached img
![image](https://user-images.githubusercontent.com/6857593/95026196-3d26e480-06ad-11eb-9b54-17d03cc97477.png)

**Comment by BBoutet1** [comment]
![Screenshot_20201006-092431](https://user-images.githubusercontent.com/59809722/95207420-d93c1300-07b5-11eb-9330-715554486e3a.png)
![Screenshot_20201006-092359](https://user-images.githubusercontent.com/59809722/95207422-d9d4a980-07b5-11eb-8cfe-09642fa223e1.png)

**Comment by BBoutet1** [comment]
@harshvchawla this problem is partially fixed on my branch. It is due to some components going outside the screen width.


Navbar overlap on the current deploy
![Screenshot_20201006-092659](https://user-images.githubusercontent.com/59809722/95207739-2f10bb00-07b6-11eb-99cc-587e83618fb1.png)
---------------------------------------------
Navbar responsive on the current branch
![Screenshot_20201006-092353](https://user-images.githubusercontent.com/59809722/95207744-2fa95180-07b6-11eb-8eca-1f3a690ba6a7.png)

**Comment by BBoutet1** [comment]
Navbar overlaps fixed through Khoi merge. Console errors not a priority.
